config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :kind, optional: true # Optional is required in Rails 6 to optional relation  
  has_one :address, dependent: :destroy
  has_many :phones, dependent: :destroy

  accepts_nested_attributes_for :address, update_only: true, allow_destroy: true
  accepts_nested_attributes_for :phones, update_only: true, reject_if: :all_blank, allow_destroy: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.order(:name).page(params[:page]).per(5)
    @my_name = "Leonardo Camp"
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address

    options_for_select_kinds
  end

  # GET /contacts/1/edit
  def edit
    options_for_select_kinds
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def options_for_select_kinds
      @kinds_option_select = Kind.all
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(
        :name, :email, :kind_id, :rmk, 
        address_attributes: [:id, :street, :city, :state, :_destroy],
        phones_attributes: [:id, :phone, :_destroy]
      )
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :kind_id, Contact.human_attribute_name("kind") %>
    <%= form.collection_select(:kind_id, @kinds_option_select, :id, :description) %>
  </div>

  <%= form.fields_for :address do |address_fields| %>    
    <div class="field">
      <%= address_fields.label :street %>
      <%= address_fields.text_field :street %>      
    </div>

    <div class="field">
      <%= address_fields.label :city %>
      <%= address_fields.text_field :city %>
    </div>

    <div class="field">
      <%= address_fields.label :state %>
      <%= address_fields.select :state, options_for_states(@contact.address.state) %>
    </div>
  <% end %>

  <div id="phones">   
    <%= form.fields_for :phones do |phones_fields| %>    
      <%= render partial: 'phone_fields', locals: { f: phones_fields } %>
    <% end %>

    <%= link_to_add_association("Adicionar Telefone", form, :phones) %>    
  </div>

  <div class="field">
    <%= form.label :rmk %>
    <%= form.text_area :rmk %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">            
    <div class="field">
        <%= f.label :phone %>
        <%= f.text_field :phone %>
        <%= link_to_remove_association "Remover", f %>
    </div>        
</div>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th><%= Contact.human_attribute_name("name") %></th>
      <th><%= Contact.human_attribute_name("email") %></th>
      <th><%= Contact.human_attribute_name("kind") %></th>
      <th><%= Contact.human_attribute_name("rmk") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr style="background: <%= cycle '#FFF', '#ddd' %>">
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.kind.description %></td>
        <td><%= contact.rmk %></td>
        <td><%= link_to t('buttons.show'), contact %></td>
        <td><%= link_to t('buttons.edit'), edit_contact_path(contact) %></td>        
        <td><%= link_to t('buttons.destroy'), contact, method: :delete, data: { confirm: t('messages.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @contacts %>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Contact.human_attribute_name("name") %>:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong><%= Contact.human_attribute_name("email") %>:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong><%= Contact.human_attribute_name("kind") %>:</strong>
  <%= @contact.kind_id %>
</p>

<p>
  <strong><%= Contact.human_attribute_name("rmk") %>:</strong>
  <%= @contact.rmk %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>